<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  	<OutputType>WinExe</OutputType>
  	<TargetFramework>net10.0-windows</TargetFramework>
  	<Nullable>enable</Nullable>
  	<ImplicitUsings>enable</ImplicitUsings>
	<UseWPF>true</UseWPF>
	<ApplicationIcon>Assets\WorldHub.ico</ApplicationIcon>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\WorldHub.ico" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorldHub.Core\WorldHub.Core.csproj" />
    <ProjectReference Include="..\WorldHub.Infrastructure\WorldHub.Infrastructure.csproj" />
    <ProjectReference Include="..\WorldHub.Network\WorldHub.Network.csproj" />
    <ProjectReference Include="..\WorldHub.Sync\WorldHub.Sync.csproj" />
  </ItemGroup>

</Project>
