<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorldHub.Core\WorldHub.Core.csproj" />
    <ProjectReference Include="..\WorldHub.Sync\WorldHub.Sync.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="FileSystem\" />
  </ItemGroup>

</Project>
